#services:
#    mer_qury_plateform.example:
#        class: MerQury\PlateformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    mer_qury_plateform.antispam:
        class: MerQury\PlateformBundle\AntiSpam\MerQuryAntiSpam
        arguments: [@mailer, %locale%, 50]
        
    mer_qury_plateform.validator.antiflood:                              

        class: MerQury\PlateformBundle\Validator\AntifloodValidator     
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: mer_qury_plateform_antiflood } 