<?php

namespace MerQury\PlateformBundle\Entity;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository {

    public function getApplicationsWithAdvert($limit) {
        
        $qb=$this->createQueryBuilder('app')->leftJoin('app.advert', 'a')->addSelect('a');
        $qb->setMaxResults($limit);
        return $qb=  $this->getQuery()->getResult();
        
    }

}
